# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgd_lm_cpp <- function(x, y, burn, gamma_0, alpha, bt_start) {
    .Call('_SGDinference_sgd_lm_cpp', PACKAGE = 'SGDinference', x, y, burn, gamma_0, alpha, bt_start)
}

sgd_qr_cpp <- function(x, y, burn, gamma_0, alpha, bt_start, tau) {
    .Call('_SGDinference_sgd_qr_cpp', PACKAGE = 'SGDinference', x, y, burn, gamma_0, alpha, bt_start, tau)
}

sgdi_lm_cpp <- function(x, y, burn, gamma_0, alpha, bt_start, inference, rss_idx) {
    .Call('_SGDinference_sgdi_lm_cpp', PACKAGE = 'SGDinference', x, y, burn, gamma_0, alpha, bt_start, inference, rss_idx)
}

sgdi_lm_cpp_new <- function(x, y, burn, gamma_0, alpha, bt_start, inference, rss_idx, x_mean, x_sd) {
    .Call('_SGDinference_sgdi_lm_cpp_new', PACKAGE = 'SGDinference', x, y, burn, gamma_0, alpha, bt_start, inference, rss_idx, x_mean, x_sd)
}

sgdi_qr_cpp <- function(x, y, burn, gamma_0, alpha, bt_start, inference, tau, rss_idx) {
    .Call('_SGDinference_sgdi_qr_cpp', PACKAGE = 'SGDinference', x, y, burn, gamma_0, alpha, bt_start, inference, tau, rss_idx)
}

