# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgd_qr_cpp <- function(x, y, burn, gamma_0, alpha, bt_start, tau) {
    .Call(`_SGDinference_sgd_qr_cpp`, x, y, burn, gamma_0, alpha, bt_start, tau)
}

sgdi_lm_cpp <- function(x, y, burn, gamma_0, alpha, bt_start, inference) {
    .Call(`_SGDinference_sgdi_lm_cpp`, x, y, burn, gamma_0, alpha, bt_start, inference)
}

sgdi_qr_cpp <- function(x, y, burn, gamma_0, alpha, bt_start, inference, tau) {
    .Call(`_SGDinference_sgdi_qr_cpp`, x, y, burn, gamma_0, alpha, bt_start, inference, tau)
}

sgdi_z_cpp <- function(x, y, z, burn, gamma_0, alpha, bt_start, inference) {
    .Call(`_SGDinference_sgdi_z_cpp`, x, y, z, burn, gamma_0, alpha, bt_start, inference)
}

