steps:
- uses: actions/checkout@master
- uses: codecov/codecov-action@v3
  with:
    token: 274652bf-dda7-45fc-9398-094d5b451e51 # not required for public repos
    files: ./coverage1.xml,./coverage2.xml # optional
    flags: unittests # optional
    name: codecov-umbrella # optional
    fail_ci_if_error: true # optional (default = false)
    verbose: true # optional (default = false)